services:
  - type: web
    name: assignment-backend
    env: node
    buildCommand: npm install
    startCommand: node test-server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production